# Generated by Django 5.2.3 on 2026-02-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=2)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('teacher', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('credit', models.FloatField()),
                ('assignment', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=2)),
                ('lab_group', models.CharField(max_length=2)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('teacher', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('credit', models.FloatField()),
            ],
        ),
    ]
